layout_spectrum: 0.4361543
color:
  saturation: 0.5458298
  lightness: 0.2263893
  brandStrength: 0.8665475
  brandColors:
    - '#111113'
    - '#FFFFFF'
    - '#D7181E'
    - '#B3B3B4'
    - '#767677'
  rhythmicContrast: 0.1782125
typography_spectrum: 0.4891871
name: Takebackthecity
